### ISSUE TITLE
关于webhook报警

### ISSUE THREAD

**Issue by Audi-dask** [Tobewont/docker-compose#1]
直接修改alertmanager/config.yml的为企业微信地址 是不是就可以调用企业微信去报警了
webhook:
    url: 企业微信机器人地址
  mention:
      all: true

**Comment by Tobewont** [comment]
> 直接修改alertmanager/config.yml的为企业微信地址 是不是就可以调用企业微信去报警了
> webhook:
> url: 企业微信机器人地址
> mention:
> all: true

通过钉钉机器人的webhook达到告警目的是dingtalk的作用，至于替换为企业微信机器人的webhook我没试过，会不会起作用不清楚，你可以替换试试，不行的话上网查找类似dingtalk的企业微信告警组件达到你的目的

**Comment by Audi-dask** [comment]
好的谢谢博主的回复 ，我自己尝试一下
