### ISSUE TITLE
能否提供grafana显示数据的json模块

### ISSUE THREAD

**Issue by wuqrmm** [Tobewont/docker-compose#2]
刚开始学习运维监控，看了您的教程，成功运行起来了，就是没有用过grafana，不知道如何才能显示教程中的监控画面，能否提供显示数据的模板！非常感谢

**Comment by Tobewont** [comment]
> 刚开始学习运维监控，看了您的教程，成功运行起来了，就是没有用过grafana，不知道如何才能显示教程中的监控画面，能否提供显示数据的模板！非常感谢

官方dashboard模板：https://grafana.com/grafana/dashboards

**Comment by Tobewont** [comment]
> > 刚开始学习运维监控，看了您的教程，成功运行起来了，就是没有用过grafana，不知道如何才能显示教程中的监控画面，能否提供显示数据的模板！非常感谢
> 
> 官方dashboard模板：https://grafana.com/grafana/dashboards

选择排行第一的中文模板：Node Exporter for Prometheus Dashboard ，模板ID是8919。

**Comment by wuqrmm** [comment]
谢谢指点，拜读了你的专栏文章学了不少，还有个小疑问，为什么普鲁米修斯只写了alert-rules文件，没写record-rules，是不是因为用了模板不需要再挂载record-rules了！

**Comment by Tobewont** [comment]
> 谢谢指点，拜读了你的专栏文章学了不少，还有个小疑问，为什么普鲁米修斯只写了alert-rules文件，没写record-rules，是不是因为用了模板不需要再挂载record-rules了！

记录规则可以预先计算经常需要或计算量大的表达式，并将其结果保存为一组新的时间序列。我没用是因为觉得没必要，你要把经常需要查询的一些指标数据写在record-rules中也可以，并不是用不用模板的原因。

**Comment by wuqrmm** [comment]
感谢回复
